### ISSUE TITLE
Week 01 Weekend - Portfolio - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career. 

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your own personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [ ] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.

### Adventure Mode

- [ ] Take the time to personalize the site.
- [ ] Keep it professional, but make it your own.

**Comment by solismc** [comment]
https://github.com/solismc/portfolio

Mark, here is my weekend project. I must say, I am quite proud of my work. I realize your say overrides my subjective, and possibly biased, opinion, lol.

Top section has some room for improvement. Separating Jason's image and text bubble. Struggled a bit to figure out how to do that.

Pleased with the Footer box. My OCD kicked-in and notice it is not aligned 100%. I inspected the elements and tried to solve the problem. I think I know where the issue is. There is a _user agent stylesheet_ that has a left side padding of 40px that I cannot figure out how to override. Once that is overridden, it should align quite nicely.

**Comment by mdewey** [comment]
Great job overall! My only real feedback is to make your commit messages a bit more meaningful that 'Sunday 5:30pm'. Make the messages more descriptive of what you did. this will help you (and your team) know what exactly you did

**Comment by solismc** [comment]
Hi Mark,

Thanks for the feedback. I will work on that.

Make it a great day!

Manuel

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/l3q2DbzOZjFYNflII/200w_d.gif)
